plugins {
    id "fabric-loom" version "1.6.12"
    id "maven-publish"
}

group = project.mod_group
version = project.mod_version
archivesBaseName = project.mod_id

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 17
}

sourceSets {
    main {
        java {
            srcDirs = ["src/fabric/java"]
            exclude "com/crowsofwar/avatar/client/**"
        }
        resources {
            srcDirs = ["src/main/resources", "src/fabric/resources"]
        }
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "mod_id", project.mod_id
    inputs.property "mod_name", project.mod_name

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "mod_id": project.mod_id,
                "mod_name": project.mod_name
    }
}

loom {
    splitEnvironmentSourceSets()
}